### ISSUE TITLE
B61 Nuclear Bomb

### ISSUE THREAD

**Issue by jmccartin** [Fullerpj/United-States-Air-Force-Mod#38]
The B61 as deployed in the B2 does not flash upon detonation, and should not have any EMP effects with a ground burst setting.  Also, if we're talking about future tech, the B61 mod 12 should be able to be deployed internally on the F35.

**Comment by Fullerpj** [comment]
I did not write the script. I didn't make it flash so that it doesn't hurt FPS..I like the EMP effect so it's here to stay. I know that it is available to the F35 but your not going to have a bunch of ppl on MP flying around dropping nukes and I wanted it to be exclusive to the B2 to give it more of a uniqueness
